// Code generated by templ@(devel) DO NOT EDIT.

package testahref

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bufio"

func render() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		err = templ.RenderScripts(ctx, w, )
		if err != nil {
			return err
		}
		_, err = w.WriteString("<a")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" href=\"javascript:alert(&#39;unaffected&#39;);\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		var_1 := `Ignored`
		_, err = w.WriteString(var_1)
		if err != nil {
			return err
		}
		_, err = w.WriteString("</a>")
		if err != nil {
			return err
		}
		err = templ.RenderScripts(ctx, w, )
		if err != nil {
			return err
		}
		_, err = w.WriteString("<a")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" href=")
		if err != nil {
			return err
		}
		_, err = w.WriteString("\"")
		if err != nil {
			return err
		}
		var var_2 templ.SafeURL = templ.URL("javascript:alert('should be sanitized')")
		_, err = w.WriteString(templ.EscapeString(string(var_2)))
		if err != nil {
			return err
		}
		_, err = w.WriteString("\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		var_3 := `Sanitized`
		_, err = w.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = w.WriteString("</a>")
		if err != nil {
			return err
		}
		err = templ.RenderScripts(ctx, w, )
		if err != nil {
			return err
		}
		_, err = w.WriteString("<a")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" href=")
		if err != nil {
			return err
		}
		_, err = w.WriteString("\"")
		if err != nil {
			return err
		}
		var var_4 templ.SafeURL = templ.SafeURL("javascript:alert('should not be sanitized')")
		_, err = w.WriteString(templ.EscapeString(string(var_4)))
		if err != nil {
			return err
		}
		_, err = w.WriteString("\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		var_5 := `Unsanitized`
		_, err = w.WriteString(var_5)
		if err != nil {
			return err
		}
		_, err = w.WriteString("</a>")
		if err != nil {
			return err
		}
		return err
	})
}

