// Code generated by templ@(devel) DO NOT EDIT.

package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bufio"
import "fmt"
import "time"

func headerTemplate(name string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		err = templ.RenderScripts(ctx, w, )
		if err != nil {
			return err
		}
		_, err = w.WriteString("<header")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" data-testid=\"headerTemplate\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<h1>")
		if err != nil {
			return err
		}
		_, err = w.WriteString(templ.EscapeString(name))
		if err != nil {
			return err
		}
		_, err = w.WriteString("</h1>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("</header>")
		if err != nil {
			return err
		}
		return err
	})
}

func footerTemplate() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		err = templ.RenderScripts(ctx, w, )
		if err != nil {
			return err
		}
		_, err = w.WriteString("<footer")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" data-testid=\"footerTemplate\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<div>")
		if err != nil {
			return err
		}
		var_1 := `&copy; `
		_, err = w.WriteString(var_1)
		if err != nil {
			return err
		}
		_, err = w.WriteString(templ.EscapeString(fmt.Sprintf("%d", time.Now().Year())))
		if err != nil {
			return err
		}
		_, err = w.WriteString("</div>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("</footer>")
		if err != nil {
			return err
		}
		return err
	})
}

func navTemplate() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		err = templ.RenderScripts(ctx, w, )
		if err != nil {
			return err
		}
		_, err = w.WriteString("<nav")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" data-testid=\"navTemplate\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<ul>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<li>")
		if err != nil {
			return err
		}
		err = templ.RenderScripts(ctx, w, )
		if err != nil {
			return err
		}
		_, err = w.WriteString("<a")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" href=\"/\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		var_2 := `Home`
		_, err = w.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = w.WriteString("</a>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("</li>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<li>")
		if err != nil {
			return err
		}
		err = templ.RenderScripts(ctx, w, )
		if err != nil {
			return err
		}
		_, err = w.WriteString("<a")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" href=\"/posts\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		var_3 := `Posts`
		_, err = w.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = w.WriteString("</a>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("</li>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("</ul>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("</nav>")
		if err != nil {
			return err
		}
		return err
	})
}

func layout(name string, content templ.Component) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		_, err = w.WriteString("<html>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<head>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<title>")
		if err != nil {
			return err
		}
		_, err = w.WriteString(templ.EscapeString(name))
		if err != nil {
			return err
		}
		_, err = w.WriteString("</title>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("</head>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<body>")
		if err != nil {
			return err
		}
		err = headerTemplate(name).Render(ctx, w.(io.Writer))
		if err != nil {
			return err
		}
		err = navTemplate().Render(ctx, w.(io.Writer))
		if err != nil {
			return err
		}
		_, err = w.WriteString("<main>")
		if err != nil {
			return err
		}
		err = content.Render(ctx, w.(io.Writer))
		if err != nil {
			return err
		}
		_, err = w.WriteString("</main>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("</body>")
		if err != nil {
			return err
		}
		err = footerTemplate().Render(ctx, w.(io.Writer))
		if err != nil {
			return err
		}
		_, err = w.WriteString("</html>")
		if err != nil {
			return err
		}
		return err
	})
}

func homeTemplate() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		err = templ.RenderScripts(ctx, w, )
		if err != nil {
			return err
		}
		_, err = w.WriteString("<div")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" data-testid=\"homeTemplate\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		var_4 := `Welcome to my website.`
		_, err = w.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = w.WriteString("</div>")
		if err != nil {
			return err
		}
		return err
	})
}

func postsTemplate(posts []Post) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		err = templ.RenderScripts(ctx, w, )
		if err != nil {
			return err
		}
		_, err = w.WriteString("<div")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" data-testid=\"postsTemplate\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		for _, p := range posts {
			err = templ.RenderScripts(ctx, w, )
			if err != nil {
				return err
			}
			_, err = w.WriteString("<div")
			if err != nil {
				return err
			}
			_, err = w.WriteString(" data-testid=\"postsTemplatePost\"")
			if err != nil {
				return err
			}
			_, err = w.WriteString(">")
			if err != nil {
				return err
			}
			err = templ.RenderScripts(ctx, w, )
			if err != nil {
				return err
			}
			_, err = w.WriteString("<div")
			if err != nil {
				return err
			}
			_, err = w.WriteString(" data-testid=\"postsTemplatePostName\"")
			if err != nil {
				return err
			}
			_, err = w.WriteString(">")
			if err != nil {
				return err
			}
			_, err = w.WriteString(templ.EscapeString(p.Name))
			if err != nil {
				return err
			}
			_, err = w.WriteString("</div>")
			if err != nil {
				return err
			}
			err = templ.RenderScripts(ctx, w, )
			if err != nil {
				return err
			}
			_, err = w.WriteString("<div")
			if err != nil {
				return err
			}
			_, err = w.WriteString(" data-testid=\"postsTemplatePostAuthor\"")
			if err != nil {
				return err
			}
			_, err = w.WriteString(">")
			if err != nil {
				return err
			}
			_, err = w.WriteString(templ.EscapeString(p.Author))
			if err != nil {
				return err
			}
			_, err = w.WriteString("</div>")
			if err != nil {
				return err
			}
			_, err = w.WriteString("</div>")
			if err != nil {
				return err
			}
		}
		_, err = w.WriteString("</div>")
		if err != nil {
			return err
		}
		return err
	})
}

func home() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		err = layout("Home", homeTemplate()).Render(ctx, w.(io.Writer))
		if err != nil {
			return err
		}
		return err
	})
}

func posts(posts []Post) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		err = layout("Posts", postsTemplate(posts)).Render(ctx, w.(io.Writer))
		if err != nil {
			return err
		}
		return err
	})
}

