// Code generated by templ@(devel) DO NOT EDIT.

package testtext

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bufio"

func BasicTemplate(name string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		_, err = w.WriteString("<div>")
		if err != nil {
			return err
		}
		var_1 := `Name: `
		_, err = w.WriteString(var_1)
		if err != nil {
			return err
		}
		_, err = w.WriteString(templ.EscapeString(name))
		if err != nil {
			return err
		}
		_, err = w.WriteString("</div>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<div>")
		if err != nil {
			return err
		}
		var_2 := `Text ` + "`" + `with backticks` + "`" + ``
		_, err = w.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = w.WriteString("</div>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<div>")
		if err != nil {
			return err
		}
		var_3 := `Text ` + "`" + `with backtick`
		_, err = w.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = w.WriteString("</div>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<div>")
		if err != nil {
			return err
		}
		var_4 := `Text ` + "`" + `with backtick alongside variable: `
		_, err = w.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = w.WriteString(templ.EscapeString(name))
		if err != nil {
			return err
		}
		_, err = w.WriteString("</div>")
		if err != nil {
			return err
		}
		return err
	})
}

