// Code generated by templ@(devel) DO NOT EDIT.

package testscriptusage

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bufio"

func withParameters(a string, b string, c int) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_withParameters_1056`,
		Function: `function __templ_withParameters_1056(a, b, c){console.log(a, b, c);}`,
		Call: templ.SafeScript(`__templ_withParameters_1056`, a, b, c),
	}
}

func withoutParameters() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_withoutParameters_6bbf`,
		Function: `function __templ_withoutParameters_6bbf(){alert("hello");}`,
		Call: templ.SafeScript(`__templ_withoutParameters_6bbf`, ),
	}
}

func Button(text string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		err = templ.RenderScripts(ctx, w, withParameters("test", text, 123), withoutParameters())
		if err != nil {
			return err
		}
		_, err = w.WriteString("<button")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" onClick=")
		if err != nil {
			return err
		}
		_, err = w.WriteString("\"")
		if err != nil {
			return err
		}
		var var_1 templ.ComponentScript = withParameters("test", text, 123)
		_, err = w.WriteString(var_1.Call)
		if err != nil {
			return err
		}
		_, err = w.WriteString("\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" onMouseover=")
		if err != nil {
			return err
		}
		_, err = w.WriteString("\"")
		if err != nil {
			return err
		}
		var var_2 templ.ComponentScript = withoutParameters()
		_, err = w.WriteString(var_2.Call)
		if err != nil {
			return err
		}
		_, err = w.WriteString("\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" type=\"button\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		_, err = w.WriteString(templ.EscapeString(text))
		if err != nil {
			return err
		}
		_, err = w.WriteString("</button>")
		if err != nil {
			return err
		}
		return err
	})
}

func ThreeButtons() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		err = Button("A").Render(ctx, w.(io.Writer))
		if err != nil {
			return err
		}
		err = Button("B").Render(ctx, w.(io.Writer))
		if err != nil {
			return err
		}
		err = templ.RenderScripts(ctx, w, )
		if err != nil {
			return err
		}
		_, err = w.WriteString("<button")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" onMouseover=\"console.log(&#39;mouseover&#39;)\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" type=\"button\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		var_3 := `Button C`
		_, err = w.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = w.WriteString("</button>")
		if err != nil {
			return err
		}
		return err
	})
}

