// Code generated by templ@(devel) DO NOT EDIT.

package testdoctype

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bufio"

func Layout(title, content string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		_, err = w.WriteString(`<!doctype html>`)
		if err != nil {
			return err
		}
		err = templ.RenderScripts(ctx, w, )
		if err != nil {
			return err
		}
		_, err = w.WriteString("<html")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" lang=\"en\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<head>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<meta")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" charset=\"UTF-8\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<meta")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" http-equiv=\"X-UA-Compatible\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" content=\"IE=edge\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<meta")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" name=\"viewport\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" content=\"width=device-width, initial-scale=1.0\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<title>")
		if err != nil {
			return err
		}
		_, err = w.WriteString(templ.EscapeString(title))
		if err != nil {
			return err
		}
		_, err = w.WriteString("</title>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("</head>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<body>")
		if err != nil {
			return err
		}
		_, err = w.WriteString(templ.EscapeString(content))
		if err != nil {
			return err
		}
		_, err = w.WriteString("</body>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("</html>")
		if err != nil {
			return err
		}
		return err
	})
}

