// Code generated by templ@(devel) DO NOT EDIT.

package example

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bufio"
import "fmt"
import "time"

func headerTemplate(name string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		err = templ.RenderScripts(ctx, w, )
		if err != nil {
			return err
		}
		_, err = w.WriteString("<header")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" data-testid=\"headerTemplate\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<h1>")
		if err != nil {
			return err
		}
		_, err = w.WriteString(templ.EscapeString(name))
		if err != nil {
			return err
		}
		_, err = w.WriteString("</h1>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("</header>")
		if err != nil {
			return err
		}
		return err
	})
}

func footerTemplate() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		err = templ.RenderScripts(ctx, w, )
		if err != nil {
			return err
		}
		_, err = w.WriteString("<footer")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" data-testid=\"footerTemplate\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		_, err = w.WriteString("<div>")
		if err != nil {
			return err
		}
		var_1 := `&copy; `
		_, err = w.WriteString(var_1)
		if err != nil {
			return err
		}
		_, err = w.WriteString(templ.EscapeString(fmt.Sprintf("%d", time.Now().Year())))
		if err != nil {
			return err
		}
		_, err = w.WriteString("</div>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("</footer>")
		if err != nil {
			return err
		}
		return err
	})
}

