// Code generated by templ@(devel) DO NOT EDIT.

package testhtml

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bufio"

func BasicTemplate(url string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		w, ok := writer.(io.StringWriter)
		if !ok {
			templw := bufio.NewWriter(writer)
			w = templw
			defer templw.Flush()
		}
		_, err = w.WriteString("<div>")
		if err != nil {
			return err
		}
		err = templ.RenderScripts(ctx, w, )
		if err != nil {
			return err
		}
		_, err = w.WriteString("<a")
		if err != nil {
			return err
		}
		_, err = w.WriteString(" href=")
		if err != nil {
			return err
		}
		_, err = w.WriteString("\"")
		if err != nil {
			return err
		}
		var var_1 templ.SafeURL = templ.URL(url)
		_, err = w.WriteString(templ.EscapeString(string(var_1)))
		if err != nil {
			return err
		}
		_, err = w.WriteString("\"")
		if err != nil {
			return err
		}
		_, err = w.WriteString(">")
		if err != nil {
			return err
		}
		var_2 := `text`
		_, err = w.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = w.WriteString("</a>")
		if err != nil {
			return err
		}
		_, err = w.WriteString("</div>")
		if err != nil {
			return err
		}
		return err
	})
}

